FROM python:3.8-alpine
MAINTAINER Gergo Kurucz "gergo.kurucz@gmail.com"
RUN apk update && apk add g++ make libffi-dev musl-dev libpq-dev
#RUN git clone https://github.com/geer26/auth_server
#COPY . /app
RUN mkdir -p /srv
WORKDIR /srv
COPY requirements.txt /srv
RUN pip3 install -r requirements.txt --no-cache-dir
ENV FLASK_RUN_HOST=0.0.0.0
EXPOSE 5001/tcp
ENTRYPOINT gunicorn -b 0.0.0.0:5001 -w 4 test:app

#docker build -t auth_server:latest .
#sudo docker run -d --net=host auth_server